import {normalizeProject,captureProject,approvedProject,currentScreen,colorFor,sizeFor,radiusFor} from './model.js';

const $ = selector => document.querySelector(selector);
const make = (tag, className = '', value = '') => { const node=document.createElement(tag); node.className=className; node.textContent=value; return node; };
const clone = value => structuredClone(value);
const api = async (url,method='GET',body) => { const response=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed');return result; };
let projects=[],current=null,selected=null,panel='edit',saveTimer=null,saveQueue=Promise.resolve(),handoffFolder='',handoffPreview='',templateList=[],canvasScale=1;
const history=new Map();
const toast=message=>{const node=$('#toast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2800);};
const state=()=>({name:current.name,...captureProject(current)});
function historyFor(){if(!history.has(current.id))history.set(current.id,{past:[],future:[]});return history.get(current.id);}
function checkpoint(){const h=historyFor();h.past.push(state());if(h.past.length>60)h.past.shift();h.future=[];updateUndo();}
function updateUndo(){const h=current?historyFor():{past:[],future:[]};$('#undo').disabled=!h.past.length;$('#redo').disabled=!h.future.length;}
function askName(title,initial){return new Promise(resolve=>{const dialog=$('#nameDialog'),form=$('#nameForm'),input=$('#nameValue');$('#nameTitle').textContent=title;input.value=initial;const finish=value=>{form.onsubmit=null;$('#cancelName').onclick=null;dialog.oncancel=null;dialog.close();resolve(value);};form.onsubmit=event=>{event.preventDefault();finish(input.value.trim());};$('#cancelName').onclick=()=>finish(null);dialog.oncancel=event=>{event.preventDefault();finish(null);};dialog.showModal();input.focus();input.select();});}
function restoreState(snapshot){Object.assign(current,clone(snapshot));selected=null;$('#projectName').value=current.name;render();scheduleSave();}
function undo(){const h=historyFor();if(!h.past.length)return;h.future.push(state());restoreState(h.past.pop());}
function redo(){const h=historyFor();if(!h.future.length)return;h.past.push(state());restoreState(h.future.pop());}
function scheduleSave(){if(!current)return;$('#saveState').textContent='Saving…';clearTimeout(saveTimer);const target=current;saveTimer=setTimeout(()=>persist(target),380);}
function persist(target){clearTimeout(saveTimer);const payload=clone(target);saveQueue=saveQueue.catch(()=>{}).then(async()=>{const saved=await api('/api/projects/'+payload.id,'PUT',payload);if(current?.id===saved.id)$('#saveState').textContent='Saved';}).catch(error=>{if(current?.id===payload.id)$('#saveState').textContent='Save failed';toast(error.message);});return saveQueue;}
function listProjects(){const host=$('#projectList');host.replaceChildren();for(const p of projects){const button=make('button','project-item'+(current?.id===p.id?' active':''),'▦  '+p.name);button.onclick=()=>openProject(p.id);host.append(button);}}
function openProject(id){if(current&&current.id!==id&&saveTimer)persist(current);current=projects.find(p=>p.id===id);selected=null;$('#projectName').value=current.name;$('#canvasTitle').textContent=current.name==='Untitled design'?'Make the idea visible.':current.name;render();listProjects();}
function selectPanel(name){panel=name;document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));for(const id of ['edit','system','brief'])$('#'+id+'Panel').hidden=id!==name;}
function listScreens(){const host=$('#screenList');host.replaceChildren();for(const screen of current.screens){const b=make('button',screen.id===current.activeScreenId?'active':'',screen.name);b.onclick=()=>{current.activeScreenId=screen.id;selected=null;scheduleSave();render();};host.append(b);}}
function fitCanvas(){if(!current)return;const screen=currentScreen(current),stage=$('#stage'),fit=$('#canvasFit'),canvas=$('#canvas'),style=getComputedStyle(stage);const roomWidth=stage.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight)-2;const roomHeight=stage.clientHeight-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom)-2;canvasScale=Math.min(1,Math.max(0.1,Math.min(roomWidth/screen.width,roomHeight/screen.height)));fit.style.width=Math.round(screen.width*canvasScale)+'px';fit.style.height=Math.round(screen.height*canvasScale)+'px';canvas.style.transform=`scale(${canvasScale})`;$('#dimensions').textContent=`${screen.width} × ${screen.height} · ${Math.round(canvasScale*100)}% view`;}
function render(){if(!current)return;const screen=currentScreen(current);listScreens();$('#canvasLabel').textContent=screen.name;$('#canvasTitle').textContent=current.name==='Untitled design'?'Make the idea visible.':current.name;const canvas=$('#canvas');canvas.replaceChildren();canvas.style.width=screen.width+'px';canvas.style.height=screen.height+'px';canvas.style.background=screen.backgroundToken?current.designSystem.colors[screen.backgroundToken]:screen.background;$('#dimensions').textContent=`${screen.width} × ${screen.height}`;const fixedFormat=!!current.templateId&&current.templateId!=='blank';$('#deviceTabs').hidden=fixedFormat;$('#templateFormat').hidden=!fixedFormat;document.querySelectorAll('[data-device]').forEach(b=>b.classList.toggle('active',b.dataset.device===(screen.width>600?'desktop':'mobile')));
  for(const item of screen.elements){const node=make('div','element '+item.type+(item.id===selected?' selected':''),item.text||'');node.style.left=item.x+'px';node.style.top=item.y+'px';node.style.width=item.w+'px';node.style.height=item.h+'px';node.style.fontSize=(sizeFor(current,item)||16)+'px';node.style.fontFamily=current.designSystem.typography.family;node.style.fontWeight=item.weight||'400';node.style.color=colorFor(current,item,'color')||'#1d2944';node.style.background=colorFor(current,item,'background')||'transparent';node.style.borderRadius=(radiusFor(current,item)||0)+'px';node.onpointerdown=event=>startDrag(event,item,node);canvas.append(node);}
  renderInspector();renderSystem();renderBrief();renderVersions();updateUndo();requestAnimationFrame(fitCanvas);
}
function startDrag(event,item,node){if(event.button!==0)return;selected=item.id;document.querySelectorAll('.element').forEach(n=>n.classList.remove('selected'));node.classList.add('selected');renderInspector();const screen=currentScreen(current);const origin={x:item.x,y:item.y,pointerX:event.clientX,pointerY:event.clientY};let moved=false;node.setPointerCapture(event.pointerId);node.onpointermove=e=>{if(!node.hasPointerCapture(e.pointerId))return;const dx=(e.clientX-origin.pointerX)/canvasScale,dy=(e.clientY-origin.pointerY)/canvasScale;if(Math.abs(dx)+Math.abs(dy)>3){if(!moved)checkpoint();moved=true;}const unit=Math.max(1,Number(current.designSystem.spacing.unit)||1);item.x=Math.max(0,Math.min(screen.width-item.w,Math.round((origin.x+dx)/unit)*unit));item.y=Math.max(0,Math.min(screen.height-item.h,Math.round((origin.y+dy)/unit)*unit));node.style.left=item.x+'px';node.style.top=item.y+'px';};node.onpointerup=()=>{node.onpointermove=null;node.onpointerup=null;if(moved){scheduleSave();renderInspector();}};}
function field(label,value,type,onChange){const wrap=make('label','field',label);const input=make(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;input.value=value??'';if(type==='number')input.min='0';input.onfocus=()=>checkpoint();input.oninput=()=>onChange(type==='number'?Number(input.value):input.value);wrap.append(input);return wrap;}
function section(text){return make('div','section-caption',text);}
function renderInspector(){const host=$('#elementFields');host.replaceChildren();const screen=currentScreen(current);const item=screen.elements.find(e=>e.id===selected);if(!item){host.append(make('div','empty-inspector','Select an element on the canvas to edit it. Shared rules live in the System tab.'));return;}
  host.append(make('div','inspector-title',item.type[0].toUpperCase()+item.type.slice(1)+' properties'));
  const change=(key,value)=>{item[key]=value;if(key==='color')delete item.colorToken;if(key==='background')delete item.backgroundToken;if(key==='fontSize')delete item.fontSizeToken;if(key==='radius')delete item.radiusToken;scheduleSave();renderCanvasOnly();};
  host.append(field('Content',item.text,'textarea',v=>change('text',v)));
  const grid=make('div','field-row');for(const [label,key] of [['X','x'],['Y','y'],['Width','w'],['Height','h']])grid.append(field(label,item[key],'number',v=>change(key,v)));host.append(grid);
  const colors=make('div','field-row');colors.append(field('Text color',/^#[0-9a-f]{6}$/i.test(colorFor(current,item,'color'))?colorFor(current,item,'color'):'#ffffff','color',v=>change('color',v)));colors.append(field('Background',/^#[0-9a-f]{6}$/i.test(colorFor(current,item,'background'))?colorFor(current,item,'background'):'#ffffff','color',v=>change('background',v)));host.append(colors);
  const more=make('div','field-row');more.append(field('Text size',sizeFor(current,item)||16,'number',v=>change('fontSize',v)));more.append(field('Corner radius',radiusFor(current,item)||0,'number',v=>change('radius',v)));host.append(more);
  const link=make('button','token-link'+(item.colorToken||item.backgroundToken?' active':''),item.colorToken||item.backgroundToken?'Using shared styles':'Use shared styles');link.onclick=()=>{checkpoint();item.colorToken=item.type==='button'?'surface':'text';item.backgroundToken=item.type==='button'?'primary':item.type==='box'?'surface':undefined;item.fontSizeToken='body';item.radiusToken=item.type==='button'?'button':item.type==='box'?'card':undefined;scheduleSave();render();};host.append(link);
  host.append(section('Element comments'));
  for(const comment of screen.comments.filter(c=>c.elementId===item.id)){const card=make('div','comment-card',comment.text+(comment.resolved?' · Resolved':''));if(!comment.resolved){const resolve=make('button','','Resolve');resolve.onclick=()=>{checkpoint();comment.resolved=true;scheduleSave();renderInspector();};card.append(document.createElement('br'),resolve);}host.append(card);}
  const entry=make('div','comment-entry');const input=make('input');input.placeholder='Comment on this element';const send=make('button','','Add');send.onclick=()=>{const text=input.value.trim();if(!text)return;checkpoint();screen.comments.push({id:crypto.randomUUID(),elementId:item.id,text,resolved:false,createdAt:new Date().toISOString()});scheduleSave();renderInspector();};entry.append(input,send);host.append(entry);
  const remove=make('button','danger','Delete element');remove.onclick=()=>{checkpoint();screen.elements=screen.elements.filter(e=>e.id!==selected);selected=null;scheduleSave();render();};host.append(remove);
}
function renderCanvasOnly(){const nodes=$('#canvas').children;const screen=currentScreen(current);for(let i=0;i<screen.elements.length;i++){const item=screen.elements[i],node=nodes[i];if(!node)continue;node.textContent=item.text||'';node.style.left=item.x+'px';node.style.top=item.y+'px';node.style.width=item.w+'px';node.style.height=item.h+'px';node.style.color=colorFor(current,item,'color')||'#1d2944';node.style.background=colorFor(current,item,'background')||'transparent';node.style.fontSize=(sizeFor(current,item)||16)+'px';node.style.borderRadius=(radiusFor(current,item)||0)+'px';}}
function renderSystem(){const host=$('#systemFields');host.replaceChildren();const system=current.designSystem;host.append(section('Colors'));for(const key of ['primary','accent','canvas','text','muted','surface'])host.append(field(key[0].toUpperCase()+key.slice(1),system.colors[key],'color',value=>{system.colors[key]=value;scheduleSave();renderCanvasOnly();const screen=currentScreen(current);if(screen.backgroundToken)$('#canvas').style.background=system.colors[screen.backgroundToken];}));host.append(section('Typography'));host.append(field('Font family',system.typography.family,'text',value=>{system.typography.family=value;scheduleSave();document.querySelectorAll('.element').forEach(n=>n.style.fontFamily=value);}));const sizes=make('div','field-row');for(const key of ['heading','body','small'])sizes.append(field(key+' size',system.typography[key],'number',value=>{system.typography[key]=value;scheduleSave();renderCanvasOnly();}));host.append(sizes);host.append(section('Spacing and corners'));const dimensions=make('div','field-row');dimensions.append(field('Spacing unit',system.spacing.unit,'number',value=>{system.spacing.unit=value;scheduleSave();}));dimensions.append(field('Button radius',system.corners.button,'number',value=>{system.corners.button=value;scheduleSave();renderCanvasOnly();}));dimensions.append(field('Card radius',system.corners.card,'number',value=>{system.corners.card=value;scheduleSave();renderCanvasOnly();}));host.append(dimensions);}
function renderBrief(){const host=$('#briefFields');host.replaceChildren();for(const [key,label,hint] of [['goal','Goal','What should the user accomplish?'],['audience','Audience','Who is this for?'],['layout','Layout','Which sections and in what order?'],['content','Content','What exact information and actions belong here?']]){const wrapper=field(label,current.briefFields[key]||'','textarea',value=>{current.briefFields[key]=value;scheduleSave();});wrapper.querySelector('textarea').placeholder=hint;host.append(wrapper);}}
function renderVersions(){const host=$('#versions');host.replaceChildren();if(!current.versions.length){host.append(make('div','empty-inspector','Save a version before sending it to implementation.'));return;}for(const version of [...current.versions].reverse().slice(0,8)){const row=make('div','version');row.append(make('span','',version.label),make('span','',new Date(version.at).toLocaleDateString()));host.append(row);}}
function addElement(type){checkpoint();const screen=currentScreen(current),system=current.designSystem,offset=screen.elements.length*13;const unit=Math.max(1,Number(system.spacing.unit)||1);const item={id:crypto.randomUUID(),type,x:Math.min(Math.round((24+offset)/unit)*unit,screen.width-170),y:Math.min(Math.round((60+offset)/unit)*unit,screen.height-70),w:type==='text'?220:180,h:55,text:type==='text'?'New text':type==='button'?'Button':'',fontSizeToken:'body',colorToken:type==='button'?'surface':'text',backgroundToken:type==='button'?'primary':type==='box'?'surface':undefined,weight:type==='button'?'700':'400',radiusToken:type==='text'?undefined:type==='button'?'button':'card'};screen.elements.push(item);selected=item.id;scheduleSave();render();}
async function newScreen(copy=false){const source=currentScreen(current),name=await askName(copy?'Duplicate screen':'New screen',copy?source.name+' copy':`Screen ${current.screens.length+1}`);if(name===null)return;checkpoint();const screen=copy?clone(source):{width:source.width,height:source.height,background:source.background,backgroundToken:source.backgroundToken,elements:[],comments:[]};screen.id=crypto.randomUUID();screen.name=name||`Screen ${current.screens.length+1}`;if(copy){screen.elements=screen.elements.map(e=>({...e,id:crypto.randomUUID()}));screen.comments=[];}current.screens.push(screen);current.activeScreenId=screen.id;selected=null;scheduleSave();render();}
function renderTemplates(){const grid=$('#templateGrid');grid.replaceChildren();for(const template of templateList){const tile=make('button','template-tile');tile.type='button';tile.title=template.description;tile.append(make('span','template-icon',template.icon),make('strong','',template.name),make('small','',template.description));tile.onclick=async()=>{tile.disabled=true;try{const project=normalizeProject(await api('/api/projects','POST',{templateId:template.id}));projects.unshift(project);$('#templateDialog').close();openProject(project.id);toast(template.name+' created');}catch(error){tile.disabled=false;toast(error.message);}};grid.append(tile);}}
$('#newProject').onclick=async()=>{try{if(!templateList.length){templateList=await api('/api/templates');renderTemplates();}$('#templateDialog').showModal();}catch(error){toast(error.message)}};
$('#projectName').onfocus=()=>checkpoint();$('#projectName').oninput=event=>{current.name=event.target.value||'Untitled design';scheduleSave();listProjects();$('#canvasTitle').textContent=current.name;};
$('#addText').onclick=()=>addElement('text');$('#addButton').onclick=()=>addElement('button');$('#addBox').onclick=()=>addElement('box');
$('#addScreen').onclick=()=>newScreen(false);$('#duplicateScreen').onclick=()=>newScreen(true);$('#renameScreen').onclick=async()=>{const screen=currentScreen(current),name=await askName('Rename screen',screen.name);if(name===null)return;checkpoint();screen.name=name||screen.name;scheduleSave();render();};
$('#undo').onclick=undo;$('#redo').onclick=redo;
document.addEventListener('keydown',event=>{const key=event.key.toLowerCase();if((event.ctrlKey||event.metaKey)&&key==='z'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){event.preventDefault();event.shiftKey?redo():undo();}});
document.querySelectorAll('[data-panel]').forEach(button=>button.onclick=()=>selectPanel(button.dataset.panel));
document.querySelectorAll('[data-device]').forEach(button=>button.onclick=()=>{if(current.templateId&&current.templateId!=='blank')return;const screen=currentScreen(current),mobile=button.dataset.device==='mobile';checkpoint();screen.width=mobile?390:1200;screen.height=mobile?844:800;scheduleSave();render();});
$('#saveVersion').onclick=async()=>{const label=await askName('Save project version',`Version ${current.versions.length+1}`);if(label===null)return;current.versions.push({label:label||`Version ${current.versions.length+1}`,at:new Date().toISOString(),snapshot:captureProject(current)});await persist(current);renderVersions();toast('Project version saved');};
$('#restoreLatest').onclick=()=>{const version=current.versions.at(-1);if(!version)return toast('No version to restore');checkpoint();const approved=approvedProject(current,version);Object.assign(current,{designSystem:approved.designSystem,briefFields:approved.briefFields,screens:approved.screens,activeScreenId:approved.activeScreenId});selected=null;scheduleSave();render();toast('Latest version restored');};
$('#handoff').onclick=async()=>{try{await persist(current);if(!current.versions.length)return toast('Save a version before handoff');const result=await api('/api/projects/'+current.id+'/handoff','POST',{});handoffFolder=result.folder;handoffPreview=result.previewUrl;$('#handoffLocation').textContent=result.folder;$('#handoffPrompt').value=result.prompt;$('#handoffDialog').showModal();}catch(error){toast(error.message)}};
$('#reviewExport').onclick=()=>{window.location.href=handoffPreview;};
$('#copyPrompt').onclick=async()=>{try{await navigator.clipboard.writeText($('#handoffPrompt').value);toast('Prompt copied');}catch{ $('#handoffPrompt').select();document.execCommand('copy');toast('Prompt copied');}};
$('#openFolder').onclick=async()=>{try{await navigator.clipboard.writeText(handoffFolder);toast('Folder path copied');}catch{toast(handoffFolder)}};
new ResizeObserver(fitCanvas).observe($('#stage'));
async function boot(){try{projects=(await api('/api/projects')).map(normalizeProject);if(!projects.length)projects=[normalizeProject(await api('/api/projects','POST',{}))];openProject(projects[0].id);}catch(error){toast('Could not load designs: '+error.message)}}boot();
