const $ = s => document.querySelector(s);
const el = (tag, attrs = {}, text = '') => { const n = document.createElement(tag); Object.assign(n, attrs); n.textContent = text; return n; };
let projects = [], current = null, selected = null, saveTimer = null, handoffFolder = '';
const api = async (url, method = 'GET', body) => { const r = await fetch(url, { method, headers: {'Content-Type':'application/json'}, body: body ? JSON.stringify(body) : undefined }); const v = await r.json(); if (!r.ok) throw Error(v.error || 'Request failed'); return v; };
const toast = msg => { $('#toast').textContent = msg; $('#toast').classList.add('show'); setTimeout(() => $('#toast').classList.remove('show'), 2700); };
const clone = v => structuredClone(v);
function showProjects() { const list = $('#projectList'); list.replaceChildren(); for (const p of projects) { const b = el('button', {className:'project-item' + (current?.id === p.id ? ' active' : '')}, '▦  ' + p.name); b.onclick = () => openProject(p.id); list.append(b); } }
function openProject(id) { current = projects.find(p => p.id === id); selected = null; $('#projectName').value = current.name; $('#brief').value = current.brief || ''; $('#canvasTitle').textContent = current.name === 'Untitled design' ? 'Make the idea visible.' : current.name; render(); showProjects(); }
function dirty() { current.updatedAt = new Date().toISOString(); $('#saveState').textContent = 'Saving…'; clearTimeout(saveTimer); saveTimer = setTimeout(save, 450); }
async function save() { if (!current) return; try { const p = await api('/api/projects/' + current.id, 'PUT', current); const i = projects.findIndex(x => x.id === p.id); projects[i] = p; current = p; $('#saveState').textContent = 'Saved'; showProjects(); } catch (e) { $('#saveState').textContent = 'Save failed'; toast(e.message); } }
function render() { const c = $('#canvas'); c.replaceChildren(); c.style.width = current.width + 'px'; c.style.height = current.height + 'px'; c.style.background = current.background; $('#dimensions').textContent = `${current.width} × ${current.height}`; document.querySelectorAll('[data-device]').forEach(b => b.classList.toggle('active', b.dataset.device === (current.width > 600 ? 'desktop' : 'mobile')));
  for (const item of current.elements) { const n = el('div', {className:'element ' + item.type + (item.id === selected ? ' selected' : '')}, item.text || ''); n.style.left=item.x+'px'; n.style.top=item.y+'px'; n.style.width=item.w+'px'; n.style.height=item.h+'px'; n.style.fontSize=(item.fontSize||16)+'px'; n.style.color=item.color||'#1d2944'; n.style.fontWeight=item.weight||'400'; n.style.background=item.background||'transparent'; n.style.borderRadius=(item.radius||0)+'px'; n.onpointerdown = ev => startDrag(ev,item,n); c.append(n); }
  renderInspector(); renderVersions();
}
function startDrag(ev,item,n) { if (ev.button !== 0) return; selected=item.id; document.querySelectorAll('.element').forEach(e=>e.classList.remove('selected')); n.classList.add('selected'); renderInspector(); let sx=ev.clientX,sy=ev.clientY,ox=item.x,oy=item.y,moved=false; n.setPointerCapture(ev.pointerId); n.onpointermove=e=>{ if (!n.hasPointerCapture(e.pointerId)) return; const dx=e.clientX-sx,dy=e.clientY-sy; if (Math.abs(dx)+Math.abs(dy)>2) moved=true; item.x=Math.max(0,Math.min(current.width-item.w,Math.round(ox+dx))); item.y=Math.max(0,Math.min(current.height-item.h,Math.round(oy+dy))); n.style.left=item.x+'px'; n.style.top=item.y+'px'; }; n.onpointerup=()=>{n.onpointermove=null;n.onpointerup=null;if(moved){dirty();renderInspector();}}; }
function field(label,key,type='text',value) { const wrap=el('label',{className:'field'},label); const input=el(type==='textarea'?'textarea':'input'); if(type!=='textarea') input.type=type; input.value=value ?? ''; if(type==='number') input.min='0'; input.oninput=()=>{ const item=current.elements.find(e=>e.id===selected); if (!item) return; item[key]=type==='number'?Number(input.value):input.value; dirty(); const selectedNode=$('.element.selected'); if(selectedNode){if(key==='text')selectedNode.textContent=item.text;else if(key==='fontSize')selectedNode.style.fontSize=item.fontSize+'px';else if(key==='color')selectedNode.style.color=item.color;else if(key==='background')selectedNode.style.background=item.background;else if(key==='radius')selectedNode.style.borderRadius=item.radius+'px';else if(['x','y','w','h'].includes(key)) selectedNode.style[{x:'left',y:'top',w:'width',h:'height'}[key]]=item[key]+'px';} }; wrap.append(input); return wrap; }
function renderInspector() { const host=$('#elementFields'); host.replaceChildren(); const item=current.elements.find(e=>e.id===selected); if(!item){host.append(el('div',{className:'empty-inspector'},'Select an element on the canvas to edit its content and appearance.')); return;}
  host.append(el('div',{className:'inspector-title'},item.type[0].toUpperCase()+item.type.slice(1)+' properties')); host.append(field('Content','text','textarea',item.text)); const row=el('div',{className:'field-row'}); row.append(field('X','x','number',item.x),field('Y','y','number',item.y),field('Width','w','number',item.w),field('Height','h','number',item.h)); host.append(row); const row2=el('div',{className:'field-row'}); row2.append(field('Text color','color','color',item.color||'#1d2944'),field('Background','background','color',item.background||'#ffffff')); host.append(row2); const row3=el('div',{className:'field-row'}); row3.append(field('Text size','fontSize','number',item.fontSize||16),field('Corner radius','radius','number',item.radius||0)); host.append(row3); const del=el('button',{className:'danger'},'Delete element'); del.onclick=()=>{ current.elements=current.elements.filter(e=>e.id!==selected);selected=null;dirty();render();}; host.append(del);
}
function renderVersions() { const host=$('#versions'); host.replaceChildren(); const versions=current.versions||[]; if(!versions.length){host.append(el('div',{className:'empty-inspector'},'No saved versions yet. Save one before handing it off.'));return;} for(const v of [...versions].reverse().slice(0,6)){const row=el('div',{className:'version'});row.append(el('span',{},v.label),el('span',{},new Date(v.at).toLocaleDateString()));host.append(row);} }
function add(type) { const offset=current.elements.length*13; const base={id:crypto.randomUUID(),type,x:Math.min(24+offset,current.width-170),y:Math.min(60+offset,current.height-70),w:type==='text'?220:180,h:type==='text'?55:55,text:type==='text'?'New text':type==='button'?'Button':'',fontSize:16,color:type==='button'?'#ffffff':'#1d2944',background:type==='button'?'#345eea':type==='box'?'#dae4ff':'transparent',weight:type==='button'?'700':'400',radius:type==='text'?0:12}; current.elements.push(base);selected=base.id;dirty();render(); }
$('#newProject').onclick=async()=>{try{const p=await api('/api/projects','POST',{});projects.unshift(p);openProject(p.id);toast('New design created');}catch(e){toast(e.message)}};
$('#projectName').oninput=e=>{current.name=e.target.value||'Untitled design';$('#canvasTitle').textContent=current.name;dirty();showProjects()};
$('#brief').oninput=e=>{current.brief=e.target.value;dirty()};
$('#addText').onclick=()=>add('text');$('#addButton').onclick=()=>add('button');$('#addBox').onclick=()=>add('box');
document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{current.width=b.dataset.device==='mobile'?390:1200;current.height=b.dataset.device==='mobile'?844:800;dirty();render()});
$('#saveVersion').onclick=async()=>{const label=prompt('Version name',`Version ${(current.versions||[]).length+1}`);if(label===null)return;current.versions ||= [];current.versions.push({label:label.trim()||`Version ${current.versions.length+1}`,at:new Date().toISOString(),snapshot:{width:current.width,height:current.height,background:current.background,brief:current.brief,elements:clone(current.elements)}});await save();renderVersions();toast('Version saved')};
$('#restoreLatest').onclick=()=>{const v=current.versions?.at(-1);if(!v)return toast('No version to restore');Object.assign(current,clone(v.snapshot));selected=null;$('#brief').value=current.brief||'';dirty();render();toast('Latest version restored')};
$('#handoff').onclick=async()=>{try{clearTimeout(saveTimer);await save();if(!current.versions?.length){toast('Save a version before handoff');return;}const h=await api('/api/projects/'+current.id+'/handoff','POST',{});handoffFolder=h.folder;$('#handoffLocation').textContent=h.folder;$('#handoffPrompt').value=h.prompt;$('#handoffDialog').showModal();}catch(e){toast(e.message)}};
$('#copyPrompt').onclick=async()=>{try{await navigator.clipboard.writeText($('#handoffPrompt').value);toast('Prompt copied')}catch{ $('#handoffPrompt').select();document.execCommand('copy');toast('Prompt copied') }};
$('#openFolder').onclick=async()=>{try{await navigator.clipboard.writeText(handoffFolder);toast('Folder path copied. Paste it into File Explorer.')}catch{toast(handoffFolder)}};
async function boot(){try{projects=await api('/api/projects');if(!projects.length){projects=[await api('/api/projects','POST',{})];}openProject(projects[0].id);}catch(e){toast('Could not load designs: '+e.message)}}boot();
